### ISSUE TITLE
Project Data Set 

### ISSUE THREAD

**Issue by AbodAly** [ivineetm007/drunk-detection#1]
Hello, I'm a senior computer science student at Ain Shames University in Egypet, majoring in scientific computing, and my graduation project is Drunk Driving Detection Using Facial Recognition. We read your paper and liked the method you used to collect the data set for the model. The data pipeline and everything. Because finding a good data set for such a project is difficult, I was hoping you could send us the visual data set links for your [DIF](https://sites.google.com/view/difproject/home). We attempted to find videos using the names provided in "[3D CNN and variants/data/video files.csv](https://github.com/ivineetm007/drunk-detection/blob/main/3D_CNN_and_variants/data/video_files.csv)," but we had little success in finding good videos to use in our project. Please keep in mind that we attempted to contact you using your [email address](vinmehta007@gmail.com) as well, but that resulted in a dead end.

**Comment by ivineetm007** [comment]
Hi,
The ```video_files.csv ``` is the data split file same as in the parent folder [split.csv](https://github.com/ivineetm007/drunk-detection/blob/main/split.csv)
Regarding data/links sharing requests over email, we usually process these requests on weekends, Please send a reminder in the same thread if I missed it somehow.
Thanks for your patience

**Comment by ivineetm007** [comment]
Closing this
