### ISSUE TITLE
Audio processing help

### ISSUE THREAD

**Issue by Kushagra0409** [ivineetm007/drunk-detection#2]
Can you please provide some details on what are the parameters for audio files, for eg. sampling rate, bitrate, channels etc. that were used during training? I need to test the model on my own audio files, but I think there is an issue with the bitrate I am using. Could you help in understanding your approach to gathering the audio files?

**Comment by ivineetm007** [comment]
Hi,
There is no constraint on the parameters of the audio. The audio features are extracted using opensmile library which handles it out of the box. You can look at the feature extraction code in this notebook- https://github.com/ivineetm007/drunk-detection/blob/main/Audio_models/audio_DNN_feature.ipynb
